spring:
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        output:
          destination: rsynu21u-transaction
        outputTopic:
          destination: rsynu21u-transaction
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/bdbootcamp
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="rsynu21u" password="tq6nhgbxo1vVvbmkN2N_TRY-19P1Akaw";
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://ms-discovery-server:8761/eureka/
server:
  port: 9018
security:
  basic:
    enable: false
management:
  security:
    enabled: false
